In [65]:
# Dépendances du notebook
%pip install openpyxl==3.1.3 pandas==3.0.3 s3fs==2026.3.0 -q

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

# Import des packages nécessaires

In [66]:
import pandas as pd
import openpyxl
from openpyxl import load_workbook 
import os

# Import des données
Les données sont disponibles sur le site [DATA AMELI](https://data.ameli.fr/pages/home/).

J’ai choisi de travailler avec deux jeux de données totalement distincts :
– une vue régionale et départementale des patients selon la pathologie, le traitement chronique ou l’épisode de soins, le sexe, la classe d’âge, la région et le département ;
– et une vue nationale portant sur les dépenses par pathologie.

Comme le fichier CSV d’origine est particulièrement volumineux, j’ai opté pour une lecture en chunks, ce qui permet de filtrer les données au fur et à mesure du chargement et d’éviter une surcharge mémoire.

J’ai ensuite enrichi ces données en les fusionnant avec un second fichier contenant les libellés des régions et des départements, afin d’obtenir un rendu plus harmonieux et plus lisible dans les visualisations.

Pour garantir un chargement fiable et éviter les problèmes liés aux chemins locaux, j’ai préféré déposer mes fichiers CSV sur Onyxia et les récupérer directement via leur URL MinIO. Cette approche assure un accès stable et reproductible aux données, quel que soit l’environnement d’exécution.

# Efectif de patients par pathologie, sexe, classe d'âge et territoire (département, région)

In [67]:
chunks = []

for chunk in pd.read_csv('https://minio.lab.sspcloud.fr/aissataa/PROJET_MEYTE/effectifs.csv', sep=';', chunksize=100_000,low_memory=False):
    filtered = chunk[(chunk['annee'] >= 2021) & (chunk['dept'] != '999')]
    chunks.append(filtered)

df_effectifs = pd.concat(chunks, ignore_index=True)
df_effectifs


#Le datasaet qui va servir de jointure pour récuperer les libelles des départements et région
df_regions_dept = pd.read_csv(
    "https://minio.lab.sspcloud.fr/aissataa/PROJET_MEYTE/LibelleRegionDept.csv",
    sep=";",
    encoding="latin1",
    usecols=["departement", "libelle_departement", "libelle_region"]
)

# Harmonisation des colonnes , les 1 devient des 01 
df_regions_dept["departement"] = df_regions_dept["departement"].astype(str).str.zfill(2)
df_effectifs["dept"] = df_effectifs["dept"].astype(str).str.zfill(2)

# Jointure des 2 :
df_final = pd.merge(
    df_effectifs, 
    df_regions_dept, 
    left_on="dept", 
    right_on="departement", 
    how="inner"
)

In [68]:
df_effectifs = df_final.copy()

In [69]:
df_effectifs

,annee,patho_niv1,patho_niv2,patho_niv3,top,cla_age_5,sexe,region,dept,Ntop,Npop,prev,Niveau prioritaire,libelle_classe_age,libelle_sexe,tri,libelle_region,departement,libelle_departement
0,2023,Maladies inflammatoires ou rares ou infection VIH,Maladies rares,Mucoviscidose,RAR_MUC_IND,95et+,9,32,59,NaN,8460,NaN,3,plus de 95 ans,tous sexes,78.0,Hauts-de-France,59,Nord
1,2023,Maladies inflammatoires ou rares ou infection VIH,Maladies rares,Mucoviscidose,RAR_MUC_IND,95et+,9,32,59,NaN,8460,NaN,3,plus de 95 ans,tous sexes,78.0,Hauts-de-France,59,Nord
2,2023,Maladies inflammatoires ou rares ou infection VIH,Maladies rares,Mucoviscidose,RAR_MUC_IND,95et+,9,32,59,NaN,8460,NaN,3,plus de 95 ans,tous sexes,78.0,Hauts-de-France,59,Nord
3,2023,Maladies inflammatoires ou rares ou infection VIH,Maladies rares,Mucoviscidose,RAR_MUC_IND,95et+,9,32,59,NaN,8460,NaN,3,plus de 95 ans,tous sexes,78.0,Hauts-de-France,59,Nord
4,2023,Maladies inflammatoires ou rares ou infection VIH,Maladies rares,Mucoviscidose,RAR_MUC_IND,95et+,9,32,59,NaN,8460,NaN,3,plus de 95 ans,tous sexes,78.0,Hauts-de-France,59,Nord
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7317445,2023,Maladies cardioneurovasculaires,Artériopathie périphérique,Artériopathie périphérique,MCV_APE_IND,45-49,2,75,64,40.0,21590,0.185,"2,3",de 45 à 49 ans,femmes,27.0,Nouvelle-Aquitaine,64,Pyrénées-Atlantiques
7317446,2023,Maladies cardioneurovasculaires,Artériopathie périphérique,Artériopathie périphérique,MCV_APE_IND,45-49,2,75,64,40.0,21590,0.185,"2,3",de 45 à 49 ans,femmes,27.0,Nouvelle-Aquitaine,64,Pyrénées-Atlantiques
7317447,2023,Maladies cardioneurovasculaires,Artériopathie périphérique,Artériopathie périphérique,MCV_APE_IND,45-49,2,75,64,40.0,21590,0.185,"2,3",de 45 à 49 ans,femmes,27.0,Nouvelle-Aquitaine,64,Pyrénées-Atlantiques
7317448,2023,Maladies cardioneurovasculaires,Artériopathie périphérique,Artériopathie périphérique,MCV_APE_IND,45-49,2,75,64,40.0,21590,0.185,"2,3",de 45 à 49 ans,femmes,27.0,Nouvelle-Aquitaine,64,Pyrénées-Atlantiques
7317449,2023,Maladies cardioneurovasculaires,Artériopathie périphérique,Artériopathie périphérique,MCV_APE_IND,45-49,2,75,64,40.0,21590,0.185,"2,3",de 45 à 49 ans,femmes,27.0,Nouvelle-Aquitaine,64,Pyrénées-Atlantiques

In [70]:


df_effectifs.head()
df_effectifs.info()

<class 'pandas.DataFrame'>
RangeIndex: 7317450 entries, 0 to 7317449
Data columns (total 19 columns):
 #   Column               Dtype
---  ------               -----
 0   annee                int64
 1   patho_niv1           str
 2   patho_niv2           str
 3   patho_niv3           str
 4   top                  str
 5   cla_age_5            str
 6   sexe                 int64
 7   region               int64
 8   dept                 str
 9   Ntop                 float64
 10  Npop                 int64
 11  prev                 float64
 12  Niveau prioritaire   str
 13  libelle_classe_age   str
 14  libelle_sexe         str
 15  tri                  float64
 16  libelle_region       str
 17  departement          str
 18  libelle_departement  str
dtypes: float64(3), int64(4), str(12)
memory usage: 1.0 GB

# Nettoyage des données

In [71]:
# Valeurs manquantes
(
    df_effectifs
    .isna()
    .sum(axis=0)
)

annee                        0
patho_niv1                   0
patho_niv2              763560
patho_niv3             1654380
top                          0
cla_age_5                    0
sexe                         0
region                       0
dept                         0
Ntop                   1950735
Npop                         0
prev                   1950735
Niveau prioritaire       95445
libelle_classe_age           0
libelle_sexe                 0
tri                      95445
libelle_region               0
departement                  0
libelle_departement          0
dtype: int64

Dans ce jeu de données, les valeurs indiquées comme NaN ne correspondent pas à de véritables valeurs manquantes. Elles apparaissent simplement lorsqu’un département ne présente aucun cas pour une pathologie donnée. Dans ce contexte, il est donc logique de remplacer ces NaN par 0, afin de refléter correctement l’absence de cas observés.

In [72]:
df_effectifs = df_effectifs.fillna(0)

# Après avoir passer les NAN à 0

In [73]:
# Valeurs manquantes
(
    df_effectifs
    .isna()
    .sum(axis=0)
)

annee                  0
patho_niv1             0
patho_niv2             0
patho_niv3             0
top                    0
cla_age_5              0
sexe                   0
region                 0
dept                   0
Ntop                   0
Npop                   0
prev                   0
Niveau prioritaire     0
libelle_classe_age     0
libelle_sexe           0
tri                    0
libelle_region         0
departement            0
libelle_departement    0
dtype: int64

### Nettoyage et préparation des données

- J’ai décidé de supprimer les parenthèses dans les variables *patho_niv2* et *patho_niv3*, car elles entraînaient un affichage peu lisible dans les visualisations et ajoutaient trop d’informations inutiles.
- Je me suis concentrée sur la France hexagonale, en incluant la Corse et les DOM.
- Les codes **99** et **999** correspondent à des agrégats régionaux ou nationaux (valeurs non rattachées à un département).  
  Comme ils faussent l’analyse territoriale, j’ai choisi de les supprimer.

In [56]:
# Nettoyage des parenthèses
cols = ["patho_niv2", "patho_niv3"]
for c in cols:
    df_effectifs.loc[:, c] = df_effectifs[c].str.replace(r"\s*\(.*\)", "", regex=True)

# Grand filtre de nettoyage , je veux gardé que la france hexagonale
liste_exclusions = ['Tout département', 'Guadeloupe ', 'Haute-Corse', 'Martinique', 'La Réunion', 'Guyane', 'Mayotte', 'Corse-du-Sud']

df_effectifs = df_effectifs[
    (~df_effectifs['libelle_departement'].astype(str).isin(liste_exclusions)) &
    
    # On enlève la région "France" qui englobe tout
    (df_effectifs['libelle_region'].astype(str) != 'FRANCE')
]

### Suppression des colonnes non utilisées

Dans cette étape, je retire les colonnes qui ne sont pas nécessaires pour l’analyse finale.  
Il s’agit principalement de variables techniques, de codes intermédiaires, ou de niveaux d’agrégation
qui ne sont pas exploités dans les visualisations (ex. : codes de tri, niveaux prioritaires, variables
de regroupement, informations redondantes ou déjà nettoyées).

L’option `errors='ignore'` permet d’éviter une erreur si certaines colonnes ont déjà été supprimées
lors d’étapes précédentes du nettoyage.

In [57]:
# Suppression des colonnes inutiles pour le nettoyage final
df = df_effectifs.drop(
    columns=[
        "Code département",
        "tri_dept",
        "tri_national",
        "region",
        "dept",
        "Niveau prioritaire_dept",
        "Niveau prioritaire_national",
        "cla_age_5",
        "type_somme",
        "top",
        "sexe",
        "dep_niv_1",
        "patho_niv1"

    ],
    errors='ignore' # Évite de faire une erreur si ça a déjà été supprimée
)

### Exploration des niveaux de pathologies

Avant d’appliquer des filtres plus précis, j’affiche les valeurs uniques de `patho_niv2` et `patho_niv3`
(en excluant les valeurs `NaN`). Cela permet de vérifier la cohérence des libellés et d’identifier
éventuels regroupements ou corrections à effectuer avant l’analyse.

In [63]:
print(df['patho_niv2'].dropna().unique())
print(df['patho_niv3'].dropna().unique())

<StringArray>
[                                                                                                  'Maladies rares',
                                                                                  'Autres affections neurologiques',
                                                                                   'Autres troubles psychiatriques',
                                                                                               'Déficience mentale',
 'Pas de pathologie repérée, traitement, maternité, hospitalisation ou traitement antalgique ou anti-inflammatoire',
                                                                                   'Total consommants tous régimes',
                                                                                    'Traitements antihypertenseurs',
                                                                  'Traitements antidépresseurs ou thymorégulateurs',
                                                                                        'Traitements anxiolytiques',
                                                                                             'Infection par le VIH',
                                                                                       'Traitements hypolipémiants',
                                                                                               'Troubles addictifs',
                                                                              'Troubles névrotiques et de l'humeur',
                                                                  'Troubles psychiatriques débutant dans l'enfance',
                                                                                            'Troubles psychotiques',
                                                                               'Maladies inflammatoires chroniques',
                                                                                                'Maladie coronaire',
                                                                                               'Maladie valvulaire',
                                                                                           'Insuffisance cardiaque',
                                                                                       'Artériopathie périphérique',
                                                                              'Autres affections cardiovasculaires',
                                                                                                         'Démences',
                                                                                                'Lésion médullaire',
                                                                                              'Sclérose en plaques',
                                                                                                        'Épilepsie',
                                                                                             'Maladie de Parkinson',
                                                                                          'Myopathie ou myasthénie',
                                                                                               'Embolie pulmonaire',
                                                                                'Maladies respiratoires chroniques',
                                                                   'Traitements antalgiques ou anti-inflammatoires',
                                                                                  'Maladies du foie ou du pancréas',
                                                                                                        'Maternité',
                                                                                          'Traitements hypnotiques',
                                                                                       'Traitements neuroleptiques',
                                                                       'Hospitalisations hors pathologies repérées',
                                                                 'Troubles du rythme ou de la conduction cardiaque',
                                                                                                          'Diabète',
                                                                                    'Hospitalisation pour Covid-19',
                                                                                       'Cancer du sein de la femme',
                                                                                     'Accident vasculaire cérébral',
                                                                                                'Dialyse chronique',
                                                                                           'Transplantation rénale',
                                                                                  'Suivi de transplantation rénale',
                                                                                                'Cancer colorectal',
                                                                                            'Cancer de la prostate',
                                                                                         'Cancer bronchopulmonaire',
                                                                                                   'Autres cancers',
                                                                  'Affections de longue durée pour d'autres causes']
Length: 48, dtype: str
<StringArray>
[                                                                                                   'Mucoviscidose',
                                                                                  'Autres affections neurologiques',
                                                                                   'Autres troubles psychiatriques',
                                                                                               'Déficience mentale',
 'Pas de pathologie repérée, traitement, maternité, hospitalisation ou traitement antalgique ou anti-inflammatoire',
                                                                                   'Total consommants tous régimes',
                                                                                    'Traitements antihypertenseurs',
                                                                  'Traitements antidépresseurs ou thymorégulateurs',
                                                                                        'Traitements anxiolytiques',
                                                                                             'Infection par le VIH',
                                                                                       'Traitements hypolipémiants',
                                                                                               'Troubles addictifs',
                                                                              'Troubles névrotiques et de l'humeur',
                                                                  'Troubles psychiatriques débutant dans l'enfance',
                                                                                            'Troubles psychotiques',
                                                                        'Autres maladies inflammatoires chroniques',
                                                                                          'Syndrome coronaire aigu',
                                                                                               'Maladie valvulaire',
                                                                                 'Insuffisance cardiaque chronique',
                                                                                      'Maladie coronaire chronique',
                                                                                       'Artériopathie périphérique',
                                                                              'Autres affections cardiovasculaires',
                                                                                                         'Démences',
                                                                                                'Lésion médullaire',
                                                                                              'Sclérose en plaques',
                                                                                                        'Épilepsie',
                                                                                             'Maladie de Parkinson',
                                                                                          'Myopathie ou myasthénie',
                                                              'Spondylarthrite ankylosante ou maladies apparentées',
                                                                     'Hémophilie ou troubles de l'hémostase graves',
                                                                  'Maladies inflammatoires chroniques intestinales',
                                                                                               'Embolie pulmonaire',
                                                                  'Polyarthrite rhumatoïde ou maladies apparentées',
                                                                    'Maladies métaboliques héréditaires ou amylose',
                                                                                     'Insuffisance cardiaque aiguë',
                                                                                'Maladies respiratoires chroniques',
                                                                   'Traitements antalgiques ou anti-inflammatoires',
                                                                                  'Maladies du foie ou du pancréas',
                                                                                                        'Maternité',
                                                                                          'Traitements hypnotiques',
                                                                                       'Traitements neuroleptiques',
                                                                       'Hospitalisations hors pathologies repérées',
                                                                 'Troubles du rythme ou de la conduction cardiaque',
                                                                                                          'Diabète',
                                                                                    'Hospitalisation pour Covid-19',
                                                                     'Cancer du sein de la femme sous surveillance',
                                                                          'Séquelle d'accident vasculaire cérébral',
                                                                                                'Dialyse chronique',
                                                                                'Accident vasculaire cérébral aigu',
                                                                                           'Transplantation rénale',
                                                                                  'Suivi de transplantation rénale',
                                                                                 'Cancer du sein de la femme actif',
                                                                              'Cancer colorectal sous surveillance',
                                                                                      'Cancer de la prostate actif',
                                                                          'Cancer de la prostate sous surveillance',
                                                                                          'Cancer colorectal actif',
                                                                       'Cancer bronchopulmonaire sous surveillance',
                                                                                            'Autres cancers actifs',
                                                                                 'Autres cancers sous surveillance',
                                                                                   'Cancer bronchopulmonaire actif',
                                                                  'Affections de longue durée pour d'autres causes']
Length: 61, dtype: str

# MISE EN PLACE DE LA PREMIRE PAGE EXCEL :

# 2 ème dataset que je vais étudier :

# Dépenses remboursées affectées à chaque pathologie

Les données présentent des informations sur les dépenses remboursées par l’ensemble des régimes d’assurance maladie et affectées à chaque pathologie, traitement chronique ou épisode de soins. Ces dépenses sont réparties en trois grandes catégories :

* les soins de ville (consultations médicales, soins infirmiers, actes de kinésithérapie, médicaments, biologie, transports, etc.)  ; 

* les hospitalisations dans les établissements de santé publics ou privés ;

* les prestations en espèces, notamment les indemnités journalières.

## Deux types d’indicateurs sont proposés pour chacune de ces catégories : 

* les dépenses totales annuelles remboursées, qui mesurent le poids financier global d’une pathologie ;

* les dépenses moyennes annuelles remboursées par patient, qui permettent d’apprécier le coût moyen associé à chaque pathologie.

Ces deux indicateurs offrent ainsi une vision complémentaire des dépenses de santé, en combinant à la fois l’impact global et la charge moyenne par patient.

In [12]:
chunks = []

for chunk in pd.read_csv('https://minio.lab.sspcloud.fr/aissataa/PROJET_MEYTE/depenses.csv', sep=';', chunksize=100_000, low_memory=False):
    filtered = chunk[chunk['annee'] >= 2021]
    chunks.append(filtered)


df_depenses = pd.concat(chunks, ignore_index=True)
df_depenses

,annee,patho_niv1,patho_niv2,patho_niv3,top,dep_niv_1,dep_niv_2,montant,Ntop,N_recourant_au_poste,montant_moy,Niveau prioritaire,tri,type_somme
0,2023,Affections de longue durée (dont 31 et 32) pou...,Affections de longue durée (dont 31 et 32) pou...,Affections de longue durée (dont 31 et 32) pou...,ALD_CAT_CAT,Hospitalisations (tous secteurs),Hospitalisations en psychiatrie secteur privé ...,0,1714310.0,5650.0,0.0,"1,2,3",16.0,Partiel
1,2023,Affections de longue durée (dont 31 et 32) pou...,Affections de longue durée (dont 31 et 32) pou...,Affections de longue durée (dont 31 et 32) pou...,ALD_CAT_CAT,Hospitalisations (tous secteurs),Hospitalisations liste en sus MCO secteur priv...,3856836,1714310.0,34840.0,2.0,"1,2,3",16.0,Partiel
2,2023,Affections de longue durée (dont 31 et 32) pou...,Affections de longue durée (dont 31 et 32) pou...,Affections de longue durée (dont 31 et 32) pou...,ALD_CAT_CAT,Hospitalisations (tous secteurs),Total hospitalisations (tous secteurs) rembour...,308350458,1714310.0,1232630.0,180.0,"1,2,3",16.0,Total
3,2023,Affections de longue durée (dont 31 et 32) pou...,Affections de longue durée (dont 31 et 32) pou...,Affections de longue durée (dont 31 et 32) pou...,ALD_CAT_CAT,Prestations en espèces,Indemnités journalières maladie et AT/MP rembo...,117367790,1714310.0,125760.0,68.0,"1,2,3",16.0,Partiel
4,2023,Affections de longue durée (dont 31 et 32) pou...,Affections de longue durée (dont 31 et 32) pou...,Affections de longue durée (dont 31 et 32) pou...,ALD_CAT_CAT,Prestations en espèces,Prestations d'invalidité remboursées,263517389,1714310.0,68580.0,154.0,"1,2,3",16.0,Partiel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7435,2022,Traitements psychotropes (hors pathologies),Traitements neuroleptiques (hors pathologies),Traitements neuroleptiques (hors pathologies),TPS_NLE_EXC,Soins de ville,Autres produits de santé remboursés,10878069,335640.0,212200.0,32.0,"2,3",55.0,Partiel
7436,2022,Traitements psychotropes (hors pathologies),Traitements neuroleptiques (hors pathologies),Traitements neuroleptiques (hors pathologies),TPS_NLE_EXC,Soins de ville,Soins de généralistes remboursés,11874138,335640.0,300910.0,35.0,"2,3",55.0,Partiel
7437,2022,Traitements psychotropes (hors pathologies),Traitements neuroleptiques (hors pathologies),Traitements neuroleptiques (hors pathologies),TPS_NLE_EXC,Soins de ville,Soins dentaires remboursés,6030821,335640.0,118450.0,18.0,"2,3",55.0,Partiel
7438,2022,Traitements psychotropes (hors pathologies),Traitements neuroleptiques (hors pathologies),Traitements neuroleptiques (hors pathologies),TPS_NLE_EXC,Soins de ville,Total soins de ville remboursés,199465569,335640.0,335630.0,594.0,"2,3",55.0,Total
7439,2022,Traitements psychotropes (hors pathologies),Traitements neuroleptiques (hors pathologies),Traitements neuroleptiques (hors pathologies),TPS_NLE_EXC,Soins de ville,Transports remboursés,21524496,335640.0,108060.0,64.0,"2,3",55.0,Partiel

# Les champs sont les suivants avant nettoyage:

In [ ]:
df.columns

# Nettoyage des données

# Valeurs manquantes

In [ ]:
(
    df
    .isna()
    .sum(axis=0)
)

In [ ]:
print(df['patho_niv2'].unique()) 
print(df['patho_niv3'].unique())

# Les champs sont les suivants après nettoyage:

In [ ]:
df.columns

In [ ]:
df

In [ ]:
df.info()

# Création du fichier Excel

Je vais créer un nouveau fichier Excel qui contiendra les données nettoyées dans un onglet "cleaned_data".

In [ ]:
import pandas as pd
from openpyxl import load_workbook
from openpyxl.worksheet.array_formula import ArrayFormula

# Charger données
df = pd.read_csv('../DATA/effectifs.csv', sep=';')
file_path = '../DATA/Dashboard_filtres.xlsx'

# Données nettoyées
with pd.ExcelWriter(file_path, engine='openpyxl') as writer:
    df.to_excel(writer, sheet_name='cleaned_data', index=False)

print("Données exportées")

# Onglet Ressources
wb = load_workbook(file_path)

if 'Ressources' not in wb.sheetnames:
    ress = wb.create_sheet('Ressources', 0)
else:
    ress = wb['Ressources']

# Titres
ress['A1'] = 'Département'
ress['B1'] = 'Année'
ress['C1'] = 'Sexe'
ress['D1'] = 'Pathologie'

# Ajout des valeurs UNIQUES
depts = sorted([str(x) for x in df['dept'].dropna().unique()])
annees = sorted(df['annee'].unique())
sexes = sorted(df['sexe'].unique())
pathos = sorted(df['patho_niv2'].dropna().unique())

# Département (colonne A)
for i, val in enumerate(depts, start=2):
    ress[f'A{i}'] = val

# Année (colonne B)
for i, val in enumerate(annees, start=2):
    ress[f'B{i}'] = val

# Sexe (colonne C)
for i, val in enumerate(sexes, start=2):
    ress[f'C{i}'] = val

# Pathologie (colonne D)
for i, val in enumerate(pathos, start=2):
    ress[f'D{i}'] = val

wb.save(file_path)
wb.close()

# DATA VIZ - EXCEL